Repository blueberry-team/blueberry_template, pull requests merged in 2024-08, with the labels that each got.

#72 회원 탈퇴 로직 추가 functions도 수정 완료
  lib/core/widget/EmailTextWidget.dart
  lib/core/widget/UserSignUpDataTextWidget.dart
  lib/feature/login/LoginScreen.dart
  lib/feature/mypage/MyPageScreen.dart
  lib/feature/user/RestoreDeletedUserScreen.dart
  lib/feature/user/provider/GetUserDeletionDateProvider.dart
  lib/feature/user/provider/GetUserDeletionRequestDateProvider.dart
  lib/feature/user/provider/GetUserEmailProviderProvider.dart
  lib/feature/user/provider/GetUserSignUpDataProvider.dart
  lib/feature/user/restore/widget/DeletionRequestUserInfoTextWidget.dart
  lib/feature/user/restore/widget/RestoreDeletionUserBottomButtonWidget.dart
  lib/feature/user/restore/widget/UserDeletionDateTextWidget.dart
  lib/feature/user/restore/widget/UserDeletionRequestDateTextWidget.dart
  lib/router/RouterProvider.dart
  lib/services/FirebaseAuthServiceProvider.dart
  lib/services/FirebaseService.dart
  lib/utils/AppStrings.dart
  lib/utils/Formatter.dart
Labels: APPROVED

#74 카메라 구조 변경 한번 더 했음
  lib/feature/camera/CameraGalleryScreen.dart
  lib/feature/camera/CameraScreen.dart
  lib/feature/camera/MyPageProfileImagePreview.dart
  lib/feature/camera/ProfileCameraPage.dart
  lib/feature/camera/ProfilePreviewScreen.dart
  lib/feature/camera/SettingInsideAccountManagerWidget.dart
  lib/feature/camera/provider/PageProvider.dart
  lib/feature/camera/service/CameraService.dart
  lib/feature/camera/widget/CameraButtonWidget.dart
  lib/feature/camera/widget/CameraErrorMessageWidget.dart
  lib/feature/camera/widget/CameraPreviewWidget.dart
  lib/feature/camera/widget/CircularProfileImagePreviewWidget.dart
  lib/feature/login/LoginScreen.dart
  lib/feature/mypage/MyPageScreen.dart
  lib/feature/mypage/widget/MyPageBottomSheet.dart
  lib/feature/notice/NoticeScreen.dart
  lib/router/RouterProvider.dart
  lib/services/camera/CameraService.dart
  lib/utils/AppStrings.dart
  lib/utils/ShadowStyle.dart
Labels: APPROVED

#68 [Test] firestore - model pet 컬렉션 검증 통합테스트 추가
  integration_test/app_test.dart
  lib/model/AnimalModel.dart
  pubspec.yaml
  test/widget_test.dart
  test_driver/integration_test.dart
Labels: APPROVED

#73 VoiceOutput 스크린 및 위젯 구조 변경
  lib/feature/voiceoutput/VoiceOutputScreen.dart
  lib/feature/voiceoutput/provider/VoiceOutputProvider.dart
  lib/feature/voiceoutput/widget/VoiceOutputItemWidget.dart
  lib/feature/voiceoutput/widget/VoiceOutputListWidget.dart
  lib/router/RouterProvider.dart
Labels: REVIEWED

#86 Feature/친구 삭제 기능
  lib/feature/friendsList/provider/FriendsListImageProvider.dart
  lib/feature/friendsList/provider/FriendsListProvider.dart
  lib/feature/friendsList/widget/BottomSheetButtonWidget.dart
  lib/feature/friendsList/widget/FriendBottomSheet.dart
  lib/feature/friendsList/widget/FriendBottomSheetLauncher.dart
  lib/feature/friendsList/widget/FriendsListViewWidget.dart
  lib/feature/friendsList/widget/PopupMenuItem.dart
  lib/feature/friendsList/widget/ShimmerSkeletonLoader.dart
  lib/feature/userreport/provider/UserReportBottomSheetWidget.dart
  lib/utils/AppStrings.dart
  pubspec.yaml
Labels: enhancement

#84 Bugfix/ 매치스크린 에러 해결 및 리펙토링
  lib/feature/match/MatchScreen.dart
  lib/feature/match/ProfileScreen.dart
  lib/feature/match/provider/MatchProvider.dart
  lib/feature/match/provider/PetImageProvider.dart
  lib/feature/match/widget/MatchFilterOptionWidget.dart
  lib/feature/match/widget/MatchProfileListWidget.dart
  lib/feature/match/widget/SwipeCardWidget.dart
  lib/model/PetProfileModel.dart
  lib/utils/AppStrings.dart
  pubspec.yaml
Labels: bug

#85 Feature/친구 목록 스크린 로직 개선
  lib/feature/friendsList/provider/FriendsListImageProvider.dart
  lib/feature/friendsList/provider/FriendsListProvider.dart
  lib/feature/friendsList/widget/BottomSheetButtonWidget.dart
  lib/feature/friendsList/widget/FriendBottomSheet.dart
  lib/feature/friendsList/widget/FriendBottomSheetLauncher.dart
  lib/feature/friendsList/widget/FriendsListViewWidget.dart
  lib/feature/friendsList/widget/PopupMenuItem.dart
  lib/feature/friendsList/widget/ShimmerSkeletonLoader.dart
  lib/feature/match/provider/MatchProvider.dart
  lib/feature/userreport/provider/UserReportBottomSheetWidget.dart
  lib/model/FriendModel.dart
  lib/utils/AppStrings.dart
Labels: enhancement

#87 좋아요&싫어요 기능 구현
  lib/core/TopScreen.dart
  lib/feature/friendsList/provider/FriendsListImageProvider.dart
  lib/feature/friendsList/provider/FriendsListProvider.dart
  lib/feature/match/MatchScreen.dart
  lib/feature/match/provider/MatchProvider.dart
  lib/feature/post/PostScreen.dart
  lib/feature/post/PostingScreen.dart
  lib/feature/post/provider/DisLikeProvider.dart
  lib/feature/post/provider/LikeProvider.dart
  lib/feature/post/provider/PostProvider.dart
  lib/feature/post/provider/UserInfoProvider.dart
  lib/feature/post/widget/PostListViewItemWidget.dart
  lib/feature/post/widget/PostListViewWidget.dart
  lib/feature/post/widget/ShimmerSkeleton.dart
  lib/model/FriendModel.dart
  lib/model/PostModel.dart
  lib/model/PostUserInfoModel.dart
Labels: enhancement
